run:
  timeout: 3m

linters:
  disable-all: true
  enable:
    - gofumpt
    - errcheck
    - gosec
    - govet
    - ineffassign
    - rowserrcheck
    - staticcheck
    - unused

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck